In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [2]:
mc_df=pd.read_csv('Mercedes (1).csv')
mc_df.shape

(4209, 378)

In [3]:
mc_df['y']

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [4]:
cat_cols=[col for col in mc_df.columns if mc_df[col].dtype=='object']## Finding catg cols
cat_cols

['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

In [5]:
mc_df['X1'].value_counts()

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
ab      3
q       3
d       3
Name: X1, dtype: int64

In [6]:
[mc_df[col].unique() for col in cat_cols]# Finding unique catg in each catg column

[array(['k', 'az', 't', 'al', 'o', 'w', 'j', 'h', 's', 'n', 'ay', 'f', 'x',
        'y', 'aj', 'ak', 'am', 'z', 'q', 'at', 'ap', 'v', 'af', 'a', 'e',
        'ai', 'd', 'aq', 'c', 'aa', 'ba', 'as', 'i', 'r', 'b', 'ax', 'bc',
        'u', 'ad', 'au', 'm', 'l', 'aw', 'ao', 'ac', 'g', 'ab'],
       dtype=object),
 array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
        'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
        'ab'], dtype=object),
 array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
        'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
        'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
        'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object),
 array(['a', 'e', 'c', 'f', 'd', 'b', 'g'], dtype=object),
 array(['d', 'b', 'c', 'a'], dtype=object),
 array(['u', 'y', 'x', 'h', 'g', 'f', 'j', 'i', 'd', 'c', 'af', 'ag', 'ab',
        'ac', 'ad', 'ae', 'ah', 'l', 'k', 'n', 'm', 'p', 'q', 's', 'r',
        'v', 'w', 'o', 'aa'], dtype=object),
 array(['j', 'l', 'd', 'h', 'i', 'a', 'g', 'c', 'k', 'e', 'f', 'b'],
       dtype=object),
 array(['o', 'x', 'e', 'n', 's', 'a', 'h', 'p', 'm', 'k', 'd', 'i', 'v',
        'j', 'b', 'q', 'w', 'g', 'y', 'l', 'f', 'u', 'r', 't', 'c'],
       dtype=object)]

In [7]:
y=mc_df['y']
#mc_df.drop(columns=['y','ID'],inplace=True)
con_cols=[col for col in mc_df.columns if mc_df[col].dtype=='int64' or mc_df[col].dtype=='float64']
# Finding cont cols

In [8]:
[mc_df[col].value_counts() for col in con_cols]# finding values in cont cols and found only two catg

[0       1
 1382    1
 5484    1
 7533    1
 1390    1
        ..
 2668    1
 621     1
 4719    1
 625     1
 2047    1
 Name: ID, Length: 4209, dtype: int64,
 89.06     7
 90.76     7
 91.88     7
 89.38     7
 90.44     6
          ..
 134.43    1
 95.92     1
 112.66    1
 93.24     1
 78.40     1
 Name: y, Length: 2545, dtype: int64,
 0    4153
 1      56
 Name: X10, dtype: int64,
 0    4209
 Name: X11, dtype: int64,
 0    3893
 1     316
 Name: X12, dtype: int64,
 0    3965
 1     244
 Name: X13, dtype: int64,
 0    2407
 1    1802
 Name: X14, dtype: int64,
 0    4207
 1       2
 Name: X15, dtype: int64,
 0    4198
 1      11
 Name: X16, dtype: int64,
 0    4177
 1      32
 Name: X17, dtype: int64,
 0    4176
 1      33
 Name: X18, dtype: int64,
 0    3790
 1     419
 Name: X19, dtype: int64,
 0    3608
 1     601
 Name: X20, dtype: int64,
 0    4198
 1      11
 Name: X21, dtype: int64,
 0    3843
 1     366
 Name: X22, dtype: int64,
 0    4122
 1      87
 Name: X23, dtype: int64,
 0    4201
 1       8
 Name: X24, dtype: int64,
 0    4188
 1      21
 Name: X26, dtype: int64,
 1    2873
 0    1336
 Name: X27, dtype: int64,
 0    4072
 1     137
 Name: X28, dtype: int64,
 0    4028
 1     181
 Name: X29, dtype: int64,
 0    4190
 1      19
 Name: X30, dtype: int64,
 0    3231
 1     978
 Name: X31, dtype: int64,
 0    4162
 1      47
 Name: X32, dtype: int64,
 0    4208
 1       1
 Name: X33, dtype: int64,
 0    4186
 1      23
 Name: X34, dtype: int64,
 0    3231
 1     978
 Name: X35, dtype: int64,
 0    4190
 1      19
 Name: X36, dtype: int64,
 0    3231
 1     978
 Name: X37, dtype: int64,
 0    4069
 1     140
 Name: X38, dtype: int64,
 0    4208
 1       1
 Name: X39, dtype: int64,
 0    4206
 1       3
 Name: X40, dtype: int64,
 0    4161
 1      48
 Name: X41, dtype: int64,
 0    4208
 1       1
 Name: X42, dtype: int64,
 0    3905
 1     304
 Name: X43, dtype: int64,
 0    4161
 1      48
 Name: X44, dtype: int64,
 0    3143
 1    1066
 Name: X45, dtype: int64,
 1    2514
 0    1695
 Name: X46, dtype: int64,
 0    4155
 1      54
 Name: X47, dtype: int64,
 0    4115
 1      94
 Name: X48, dtype: int64,
 0    3695
 1     514
 Name: X49, dtype: int64,
 0    3308
 1     901
 Name: X50, dtype: int64,
 1    3038
 0    1171
 Name: X51, dtype: int64,
 0    4031
 1     178
 Name: X52, dtype: int64,
 0    4180
 1      29
 Name: X53, dtype: int64,
 0    4026
 1     183
 Name: X54, dtype: int64,
 0    4187
 1      22
 Name: X55, dtype: int64,
 0    4120
 1      89
 Name: X56, dtype: int64,
 0    4153
 1      56
 Name: X57, dtype: int64,
 1    2420
 0    1789
 Name: X58, dtype: int64,
 0    4206
 1       3
 Name: X59, dtype: int64,
 0    4203
 1       6
 Name: X60, dtype: int64,
 1    4015
 0     194
 Name: X61, dtype: int64,
 0    4184
 1      25
 Name: X62, dtype: int64,
 0    4161
 1      48
 Name: X63, dtype: int64,
 0    2630
 1    1579
 Name: X64, dtype: int64,
 0    4200
 1       9
 Name: X65, dtype: int64,
 0    4095
 1     114
 Name: X66, dtype: int64,
 0    4201
 1       8
 Name: X67, dtype: int64,
 0    3900
 1     309
 Name: X68, dtype: int64,
 0    4083
 1     126
 Name: X69, dtype: int64,
 1    3872
 0     337
 Name: X70, dtype: int64,
 0    3773
 1     436
 Name: X71, dtype: int64,
 0    4125
 1      84
 Name: X73, dtype: int64,
 1    4206
 0       3
 Name: X74, dtype: int64,
 0    4057
 1     152
 Name: X75, dtype: int64,
 0    4026
 1     183
 Name: X76, dtype: int64,
 0    4156
 1      53
 Name: X77, dtype: int64,
 0    4185
 1      24
 Name: X78, dtype: int64,
 0    4103
 1     106
 Name: X79, dtype: int64,
 1    3986
 0     223
 Name: X80, dtype: int64,
 0    3245
 1     964
 Name: X81, dtype: int64,
 0    4137
 1      72
 Name: X82, dtype: int64,
 0    4204
 1       5
 Name: X83, dtype: int64,
 0    3773
 1     436
 Name: X84, dtype: int64,
 0    2491
 1    1718
 Name: X85, dtype: int64,
 0    4203
 1       6
 Name: X86, dtype: int64,
 0    4205
 1       4
 Name: X87, dtype: int64,
 0    4179
 1      30
 Name: X88, dtype: int64,
 0    4206
 1       3
 Name: X89, dtype: int64,
 0    4178
 1      31
 Name: X90, dtype: int64,
 0    4202
 1       7
 Name: X91, dtype: int64,
 0    4205
 1       4
 Name: X92, dtype: int64,
 0    4209
 Name: X93, dtype: int64,
 0    4178
 1      31
 Name: X94, dtype: int64,
 0    4208
 1       1
 Name: X95, dtype: int64,
 1    3191
 0    1018
 Name: X96, dtype: int64,
 0    4191
 1      18
 Name: X97, dtype: int64,
 1    3967
 0     242
 Name: X98, dtype: int64,
 0    4173
 1      36
 Name: X99, dtype: int64,
 1    2905
 0    1304
 Name: X100, dtype: int64,
 1    3938
 0     271
 Name: X101, dtype: int64,
 0    4180
 1      29
 Name: X102, dtype: int64,
 1    3302
 0     907
 Name: X103, dtype: int64,
 0    4201
 1       8
 Name: X104, dtype: int64,
 0    4199
 1      10
 Name: X105, dtype: int64,
 0    4154
 1      55
 Name: X106, dtype: int64,
 0    4209
 Name: X107, dtype: int64,
 0    4147
 1      62
 Name: X108, dtype: int64,
 0    4039
 1     170
 Name: X109, dtype: int64,
 0    4205
 1       4
 Name: X110, dtype: int64,
 1    4103
 0     106
 Name: X111, dtype: int64,
 0    4197
 1      12
 Name: X112, dtype: int64,
 0    4115
 1      94
 Name: X113, dtype: int64,
 0    3594
 1     615
 Name: X114, dtype: int64,
 0    3007
 1    1202
 Name: X115, dtype: int64,
 0    3381
 1     828
 Name: X116, dtype: int64,
 0    4002
 1     207
 Name: X117, dtype: int64,
 1    2619
 0    1590
 Name: X118, dtype: int64,
 1    2619
 0    1590
 Name: X119, dtype: int64,
 1    4031
 0     178
 Name: X120, dtype: int64,
 0    4179
 1      30
 Name: X122, dtype: int64,
 0    4198
 1      11
 Name: X123, dtype: int64,
 0    4207
 1       2
 Name: X124, dtype: int64,
 0    4196
 1      13
 Name: X125, dtype: int64,
 0    4045
 1     164
 Name: X126, dtype: int64,
 0    2125
 1    2084
 Name: X127, dtype: int64,
 1    4034
 0     175
 Name: X128, dtype: int64,
 0    3693
 1     516
 Name: X129, dtype: int64,
 0    4034
 1     175
 Name: X130, dtype: int64,
 0    4097
 1     112
 Name: X131, dtype: int64,
 1    2898
 0    1311
 Name: X132, dtype: int64,
 0    3686
 1     523
 Name: X133, dtype: int64,
 0    4115
 1      94
 Name: X134, dtype: int64,
 0    4095
 1     114
 Name: X135, dtype: int64,
 1    4026
 0     183
 Name: X136, dtype: int64,
 1    2449
 0    1760
 Name: X137, dtype: int64,
 0    4037
 1     172
 Name: X138, dtype: int64,
 0    3828
 1     381
 Name: X139, dtype: int64,
 0    4039
 1     170
 Name: X140, dtype: int64,
 0    4149
 1      60
 Name: X141, dtype: int64,
 1    3242
 0     967
 Name: X142, dtype: int64,
 0    4048
 1     161
 Name: X143, dtype: int64,
 1    3401
 0     808
 Name: X144, dtype: int64,
 0    4203
 1       6
 Name: X145, dtype: int64,
 0    4037
 1     172
 Name: X146, dtype: int64,
 0    4115
 1      94
 Name: X147, dtype: int64,
 0    4020
 1     189
 Name: X148, dtype: int64,
 1    3335
 0     874
 Name: X150, dtype: int64,
 0    3849
 1     360
 Name: X151, dtype: int64,
 0    4073
 1     136
 Name: X152, dtype: int64,
 0    4206
 1       3
 Name: X153, dtype: int64,
 0    3330
 1     879
 Name: X154, dtype: int64,
 0    3887
 1     322
 Name: X155, dtype: int64,
 1    3019
 0    1190
 Name: X156, dtype: int64,
 0    3019
 1    1190
 Name: X157, dtype: int64,
 0    3242
 1     967
 Name: X158, dtype: int64,
 0    4152
 1      57
 Name: X159, dtype: int64,
 0    4204
 1       5
 Name: X160, dtype: int64,
 0    3377
 1     832
 Name: X161, dtype: int64,
 0    4037
 1     172
 Name: X162, dtype: int64,
 0    2932
 1    1277
 Name: X163, dtype: int64,
 0    3946
 1     263
 Name: X164, dtype: int64,
 0    4190
 1      19
 Name: X165, dtype: int64,
 0    4069
 1     140
 Name: X166, dtype: int64,
 0    4205
 1       4
 Name: X167, dtype: int64,
 0    3069
 1    1140
 Name: X168, dtype: int64,
 0    4181
 1      28
 Name: X169, dtype: int64,
 0    4107
 1     102
 Name: X170, dtype: int64,
 1    2767
 0    1442
 Name: X171, dtype: int64,
 0    4184
 1      25
 Name: X172, dtype: int64,
 0    4168
 1      41
 Name: X173, dtype: int64,
 0    4136
 1      73
 Name: X174, dtype: int64,
 0    4115
 1      94
 Name: X175, dtype: int64,
 0    4137
 1      72
 Name: X176, dtype: int64,
 0    3998
 1     211
 Name: X177, dtype: int64,
 1    2346
 0    1863
 Name: X178, dtype: int64,
 0    4007
 1     202
 Name: X179, dtype: int64,
 0    3544
 1     665
 Name: X180, dtype: int64,
 0    3814
 1     395
 Name: X181, dtype: int64,
 0    3762
 1     447
 Name: X182, dtype: int64,
 0    4192
 1      17
 Name: X183, dtype: int64,
 0    4203
 1       6
 Name: X184, dtype: int64,
 0    4130
 1      79
 Name: X185, dtype: int64,
 1    2256
 0    1953
 Name: X186, dtype: int64,
 0    2439
 1    1770
 Name: X187, dtype: int64,
 1    3853
 0     356
 Name: X189, dtype: int64,
 0    4208
 1       1
 Name: X190, dtype: int64,
 0    2227
 1    1982
 Name: X191, dtype: int64,
 0    4199
 1      10
 Name: X192, dtype: int64,
 0    2256
 1    1953
 Name: X194, dtype: int64,
 0    4160
 1      49
 Name: X195, dtype: int64,
 0    4166
 1      43
 Name: X196, dtype: int64,
 0    4073
 1     136
 Name: X197, dtype: int64,
 0    4112
 1      97
 Name: X198, dtype: int64,
 0    4197
 1      12
 Name: X199, dtype: int64,
 0    4181
 1      28
 Name: X200, dtype: int64,
 0    3461
 1     748
 Name: X201, dtype: int64,
 0    3193
 1    1016
 Name: X202, dtype: int64,
 0    4138
 1      71
 Name: X203, dtype: int64,
 0    4208
 1       1
 Name: X204, dtype: int64,
 1    4208
 0       1
 Name: X205, dtype: int64,
 0    4128
 1      81
 Name: X206, dtype: int64,
 0    4208
 1       1
 Name: X207, dtype: int64,
 0    3944
 1     265
 Name: X208, dtype: int64,
 1    3782
 0     427
 Name: X209, dtype: int64,
 0    4208
 1       1
 Name: X210, dtype: int64,
 0    4146
 1      63
 Name: X211, dtype: int64,
 0    4186
 1      23
 Name: X212, dtype: int64,
 0    4201
 1       8
 Name: X213, dtype: int64,
 0    4180
 1      29
 Name: X214, dtype: int64,
 0    3794
 1     415
 Name: X215, dtype: int64,
 0    4184
 1      25
 Name: X216, dtype: int64,
 0    4178
 1      31
 Name: X217, dtype: int64,
 0    2894
 1    1315
 Name: X218, dtype: int64,
 0    3925
 1     284
 Name: X219, dtype: int64,
 1    2362
 0    1847
 Name: X220, dtype: int64,
 0    4175
 1      34
 Name: X221, dtype: int64,
 0    4115
 1      94
 Name: X222, dtype: int64,
 1    2337
 0    1872
 Name: X223, dtype: int64,
 0    2873
 1    1336
 Name: X224, dtype: int64,
 0    3801
 1     408
 Name: X225, dtype: int64,
 0    4073
 1     136
 Name: X226, dtype: int64,
 0    4196
 1      13
 Name: X227, dtype: int64,
 0    4045
 1     164
 Name: X228, dtype: int64,
 1    4041
 0     168
 Name: X229, dtype: int64,
 0    4187
 1      22
 Name: X230, dtype: int64,
 0    4141
 1      68
 Name: X231, dtype: int64,
 0    4028
 1     181
 Name: X232, dtype: int64,
 0    4209
 Name: X233, dtype: int64,
 0    3360
 1     849
 Name: X234, dtype: int64,
 0    4209
 Name: X235, dtype: int64,
 0    4207
 1       2
 Name: X236, dtype: int64,
 0    4181
 1      28
 Name: X237, dtype: int64,
 1    3856
 0     353
 Name: X238, dtype: int64,
 0    4180
 1      29
 Name: X239, dtype: int64,
 0    4197
 1      12
 Name: X240, dtype: int64,
 0    3800
 1     409
 Name: X241, dtype: int64,
 0    4178
 1      31
 Name: X242, dtype: int64,
 0    4179
 1      30
 Name: X243, dtype: int64,
 0    3773
 1     436
 Name: X244, dtype: int64,
 0    4206
 1       3
 Name: X245, dtype: int64,
 0    2486
 1    1723
 Name: X246, dtype: int64,
 0    3193
 1    1016
 Name: X247, dtype: int64,
 0    4203
 1       6
 Name: X248, dtype: int64,
 0    4177
 1      32
 Name: X249, dtype: int64,
 1    2327
 0    1882
 Name: X250, dtype: int64,
 0    2550
 1    1659
 Name: X251, dtype: int64,
 0    4206
 1       3
 Name: X252, dtype: int64,
 0    4203
 1       6
 Name: X253, dtype: int64,
 0    4187
 1      22
 Name: X254, dtype: int64,
 0    4127
 1      82
 Name: X255, dtype: int64,
 0    3901
 1     308
 Name: X256, dtype: int64,
 0    4208
 1       1
 Name: X257, dtype: int64,
 0    4199
 1      10
 Name: X258, dtype: int64,
 0    4208
 1       1
 Name: X259, dtype: int64,
 0    4208
 1       1
 Name: X260, dtype: int64,
 0    2443
 1    1766
 Name: X261, dtype: int64,
 0    4203
 1       6
 Name: X262, dtype: int64,
 1    4028
 0     181
 Name: X263, dtype: int64,
 0    4043
 1     166
 Name: X264, dtype: int64,
 1    3811
 0     398
 Name: X265, dtype: int64,
 0    4203
 1       6
 Name: X266, dtype: int64,
 0    4171
 1      38
 Name: X267, dtype: int64,
 0    4209
 Name: X268, dtype: int64,
 0    4207
 1       2
 Name: X269, dtype: int64,
 0    4208
 1       1
 Name: X270, dtype: int64,
 0    4200
 1       9
 Name: X271, dtype: int64,
 0    4051
 1     158
 Name: X272, dtype: int64,
 1    3031
 0    1178
 Name: X273, dtype: int64,
 0    4167
 1      42
 Name: X274, dtype: int64,
 1    3059
 0    1150
 Name: X275, dtype: int64,
 0    4047
 1     162
 Name: X276, dtype: int64,
 0    4203
 1       6
 Name: X277, dtype: int64,
 0    4207
 1       2
 Name: X278, dtype: int64,
 0    4028
 1     181
 Name: X279, dtype: int64,
 0    4208
 1       1
 Name: X280, dtype: int64,
 0    4198
 1      11
 Name: X281, dtype: int64,
 0    4192
 1      17
 Name: X282, dtype: int64,
 0    3617
 1     592
 Name: X283, dtype: int64,
 0    4036
 1     173
 Name: X284, dtype: int64,
 0    3343
 1     866
 Name: X285, dtype: int64,
 0    3979
 1     230
 Name: X286, dtype: int64,
 0    4142
 1      67
 Name: X287, dtype: int64,
 0    4208
 1       1
 Name: X288, dtype: int64,
 0    4209
 Name: X289, dtype: int64,
 0    4209
 Name: X290, dtype: int64,
 0    4165
 1      44
 Name: X291, dtype: int64,
 0    4171
 1      38
 Name: X292, dtype: int64,
 0    4209
 Name: X293, dtype: int64,
 0    3683
 1     526
 Name: X294, dtype: int64,
 0    4208
 1       1
 Name: X295, dtype: int64,
 0    4208
 1       1
 Name: X296, dtype: int64,
 0    4209
 Name: X297, dtype: int64,
 0    4190
 1      19
 Name: X298, dtype: int64,
 0    4190
 1      19
 Name: X299, dtype: int64,
 0    3338
 1     871
 Name: X300, dtype: int64,
 0    4012
 1     197
 Name: X301, dtype: int64,
 0    4161
 1      48
 Name: X302, dtype: int64,
 1    3890
 0     319
 Name: X304, dtype: int64,
 0    4153
 1      56
 Name: X305, dtype: int64,
 0    4025
 1     184
 Name: X306, dtype: int64,
 0    4200
 1       9
 Name: X307, dtype: int64,
 0    4169
 1      40
 Name: X308, dtype: int64,
 0    4179
 1      30
 Name: X309, dtype: int64,
 0    4198
 1      11
 Name: X310, dtype: int64,
 1    2519
 0    1690
 Name: X311, dtype: int64,
 0    4191
 1      18
 Name: X312, dtype: int64,
 0    2942
 1    1267
 Name: X313, dtype: int64,
 0    2392
 1    1817
 Name: X314, dtype: int64,
 0    4088
 1     121
 Name: X315, dtype: int64,
 0    3386
 1     823
 Name: X316, dtype: int64,
 0    4177
 1      32
 Name: X317, dtype: int64,
 0    4206
 1       3
 Name: X318, dtype: int64,
 0    4207
 1       2
 Name: X319, dtype: int64,
 0    4179
 1      30
 Name: X320, dtype: int64,
 0    3204
 1    1005
 Name: X321, dtype: int64,
 0    4117
 1      92
 Name: X322, dtype: int64,
 0    4170
 1      39
 Name: X323, dtype: int64,
 1    2420
 0    1789
 Name: X324, dtype: int64,
 0    4185
 1      24
 Name: X325, dtype: int64,
 0    4073
 1     136
 Name: X326, dtype: int64,
 0    3669
 1     540
 Name: X327, dtype: int64,
 0    4040
 1     169
 Name: X328, dtype: int64,
 0    2377
 1    1832
 Name: X329, dtype: int64,
 0    4209
 Name: X330, dtype: int64,
 0    3973
 1     236
 Name: X331, dtype: int64,
 0    4206
 1       3
 Name: X332, dtype: int64,
 0    4108
 1     101
 Name: X333, dtype: int64,
 0    2262
 1    1947
 Name: X334, dtype: int64,
 0    4194
 1      15
 Name: X335, dtype: int64,
 0    3673
 1     536
 Name: X336, dtype: int64,
 1    2174
 0    2035
 Name: X337, dtype: int64,
 0    4180
 1      29
 Name: X338, dtype: int64,
 0    4208
 1       1
 Name: X339, dtype: int64,
 0    4115
 1      94
 Name: X340, dtype: int64,
 0    4175
 1      34
 Name: X341, dtype: int64,
 0    4115
 1      94
 Name: X342, dtype: int64,
 0    3879
 1     330
 Name: X343, dtype: int64,
 0    4173
 1      36
 Name: X344, dtype: int64,
 0    4115
 1      94
 Name: X345, dtype: int64,
 0    4009
 1     200
 Name: X346, dtype: int64,
 0    4209
 Name: X347, dtype: int64,
 1    3987
 0     222
 Name: X348, dtype: int64,
 0    4020
 1     189
 Name: X349, dtype: int64,
 0    2783
 1    1426
 Name: X350, dtype: int64,
 0    2958
 1    1251
 Name: X351, dtype: int64,
 0    3981
 1     228
 Name: X352, dtype: int64,
 0    4200
 1       9
 Name: X353, dtype: int64,
 0    3355
 1     854
 Name: X354, dtype: int64,
 0    2608
 1    1601
 Name: X355, dtype: int64,
 0    3452
 1     757
 Name: X356, dtype: int64,
 0    4204
 1       5
 Name: X357, dtype: int64,
 0    2412
 1    1797
 Name: X358, dtype: int64,
 0    4075
 1     134
 Name: X359, dtype: int64,
 0    3887
 1     322
 Name: X360, dtype: int64,
 1    4066
 0     143
 Name: X361, dtype: int64,
 1    2190
 0    2019
 Name: X362, dtype: int64,
 1    3173
 0    1036
 Name: X363, dtype: int64,
 0    4197
 1      12
 Name: X364, dtype: int64,
 0    4197
 1      12
 Name: X365, dtype: int64,
 0    4204
 1       5
 Name: X366, dtype: int64,
 0    3991
 1     218
 Name: X367, dtype: int64,
 0    3945
 1     264
 Name: X368, dtype: int64,
 0    4207
 1       2
 Name: X369, dtype: int64,
 0    4181
 1      28
 Name: X370, dtype: int64,
 0    4149
 1      60
 Name: X371, dtype: int64,
 0    4207
 1       2
 Name: X372, dtype: int64,
 0    4128
 1      81
 Name: X373, dtype: int64,
 0    3252
 1     957
 Name: X374, dtype: int64,
 0    2867
 1    1342
 Name: X375, dtype: int64,
 0    3968
 1     241
 Name: X376, dtype: int64,
 0    2884
 1    1325
 Name: X377, dtype: int64,
 0    4122
 1      87
 Name: X378, dtype: int64,
 0    4169
 1      40
 Name: X379, dtype: int64,
 0    4175
 1      34
 Name: X380, dtype: int64,
 0    4177
 1      32
 Name: X382, dtype: int64,
 0    4202
 1       7
 Name: X383, dtype: int64,
 0    4207
 1       2
 Name: X384, dtype: int64,
 0    4203
 1       6
 Name: X385, dtype: int64]

In [9]:
tot_cols=con_cols+cat_cols
mc_df.columns,len(tot_cols)

(Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
        ...
        'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
        'X385'],
       dtype='object', length=378),
 378)

In [10]:
t_df=mc_df.copy()
t_df.drop(columns=cat_cols,inplace=True)

In [11]:
temp_df=pd.DataFrame({'cols':t_df.columns,'var':np.var(mc_df[con_cols])})
one_var_catg_cols=list(temp_df[temp_df['var']==0.0]['cols'])

In [12]:
for col in con_cols:
    mc_df[col]=mc_df[col].astype(object)
# converting all cont cols to catg cols

In [13]:
cat_cols=[col for col in mc_df.columns if mc_df[col].dtype=='object']
len(cat_cols)

378

In [14]:
[col for col in mc_df.columns if mc_df[col].dtype=='int64' or mc_df[col].dtype=='float64']

[]

In [15]:
mc_df['X93'].value_counts()
# single value catg col

0    4209
Name: X93, dtype: int64

In [16]:
cols_drop_uniq_val=[]
for col in con_cols:
    if len(mc_df[col].value_counts()) ==1 or len(mc_df[col].value_counts())==mc_df.shape[0]:
        cols_drop_uniq_val.append(col)
cols_drop_uniq_val

['ID',
 'X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347']

In [17]:
mc_df.drop(columns=one_var_catg_cols,inplace=True)
# droping all single value catg cols

In [18]:
mc_df.drop(columns=['y','ID'],inplace=True)

In [19]:
x_train,x_test,y_train,y_test=train_test_split(mc_df,y,random_state=63,test_size=0.2)

In [20]:
[col for col in mc_df.columns if mc_df[col].dtype=='int64' or mc_df[col].dtype=='float64']

[]

In [21]:
ful_cat_cols=[col for col in mc_df.columns if mc_df[col].dtype=='object']
len(ful_cat_cols)

364

In [22]:
x_train[ful_cat_cols].isnull().sum().any()## no missing values

False

In [23]:
cat_encd_train= pd.get_dummies(x_train[ful_cat_cols])
cat_encd_test=pd.get_dummies(x_test[ful_cat_cols])

In [24]:
cat_encd_train.shape,cat_encd_test.shape

((3367, 903), (842, 847))

In [25]:
cat_encd_train_final,cat_encd_test_final=cat_encd_train.align(cat_encd_test,join='inner',axis=1)
cat_encd_train_final.shape###aligning train & test data one hot encoded catg columns due to unqual no of columns i.e no of cilumns would differ for that we align to get same

(3367, 843)

In [26]:
dtree_reg=DecisionTreeRegressor()

In [27]:
dtree_reg.fit(cat_encd_train_final,y_train)

DecisionTreeRegressor()

In [28]:
y_test_pred=dtree_reg.predict(cat_encd_test_final)
y_test_pred

array([ 75.38      ,  98.5       ,  91.68      ,  98.61      ,
       108.35      , 109.25      ,  90.805     , 104.92      ,
       117.71      , 116.04      ,  89.09      ,  90.725     ,
       116.75      , 158.53      , 115.84125   , 100.32      ,
       100.47      ,  89.97      , 115.72      ,  93.12      ,
       128.58      ,  91.62      , 111.47      ,  88.08      ,
        97.86      ,  93.43      , 110.23      ,  92.2375    ,
       114.73      , 105.82      ,  99.74      ,  90.11      ,
        84.76      ,  86.41      , 101.99      ,  97.87      ,
       108.3       ,  88.54      ,  99.4       , 107.9       ,
       108.68      ,  98.84      , 101.17      , 108.12      ,
       107.47      , 111.38      ,  97.36      , 111.01      ,
       109.93      , 113.64      ,  98.1       ,  90.37      ,
        88.99      ,  89.91      ,  90.46      , 113.88      ,
        89.75      , 100.47      , 101.14      ,  92.46      ,
        90.25      ,  92.38      , 100.13      ,  77.64      ,
       106.28      ,  82.44      ,  75.26      , 112.42      ,
        88.4       ,  93.8       ,  90.22      ,  78.01      ,
       115.15      ,  97.37      , 108.59      , 109.02      ,
        96.59333333, 106.37      , 108.38      , 110.47      ,
       100.1       , 135.13      ,  88.1       ,  89.34      ,
        86.81      , 103.93      , 107.64      , 109.93      ,
        87.33      ,  96.16      , 106.87      , 108.75      ,
       107.98      ,  92.32      , 109.61      , 112.55      ,
       104.65      ,  89.81      , 101.39      ,  94.54      ,
       100.5       ,  87.8       , 111.14      ,  74.87      ,
       109.72      ,  88.88      , 113.24      , 100.64      ,
        93.45      ,  72.94      ,  98.32      , 106.        ,
        93.29      , 111.41      ,  97.07      ,  93.09      ,
       100.89      , 111.74      , 118.71      , 128.8       ,
       108.35      , 117.635     , 109.43      , 108.06      ,
        95.35      ,  91.16      , 112.2       ,  92.22      ,
        90.83      ,  94.21      , 109.53      , 113.4       ,
       112.19      , 112.34      , 103.03      , 106.52      ,
        74.87      , 100.68      , 112.76      , 119.94      ,
        90.08      , 110.15      ,  98.95      ,  90.16      ,
       110.07      , 119.2       , 121.28      ,  92.07      ,
        88.28      , 112.57      , 100.63      ,  89.99      ,
       106.62      ,  90.44      , 112.19      ,  77.25      ,
        91.63      , 117.65      ,  94.8       ,  93.77      ,
       109.34      , 115.73      ,  88.68      ,  94.51      ,
       110.47      , 104.45      ,  84.65      , 133.36      ,
       111.91      ,  99.68      , 108.06      ,  98.07666667,
       116.87      ,  99.06      ,  98.28      ,  88.46      ,
       105.54      ,  89.1       ,  89.22      ,  98.92      ,
        75.86      , 115.82      , 100.44      ,  76.64      ,
        93.27      ,  85.97      ,  89.73      , 119.38      ,
        87.76      ,  89.54      ,  89.68      , 108.94      ,
        96.98      ,  91.39      ,  93.45      ,  93.64      ,
        89.1       ,  89.9       ,  91.82      , 108.75      ,
        99.175     ,  87.85      , 113.43      , 107.03      ,
       101.17      , 110.76      ,  93.76      , 122.28      ,
        93.2975    , 101.32      ,  97.33      ,  93.78      ,
        73.4       , 102.91      ,  96.92      , 108.26      ,
       113.75      , 104.91      ,  76.78      ,  88.08      ,
       107.45      , 108.35      ,  99.39333333,  99.78      ,
       117.81      ,  99.95      , 120.12      ,  89.61      ,
       114.21      , 117.24      ,  89.6       , 109.13      ,
        98.16      , 109.99      ,  84.85      , 105.67      ,
        98.25      ,  90.71      ,  89.53      ,  89.44      ,
       100.98      , 109.05      ,  86.98      , 101.18      ,
        88.51      ,  97.77      ,  91.07      , 101.29      ,
        97.16      , 105.7       , 107.885     , 109.72      ,
        96.38      , 108.085     ,  90.58      ,  86.73      ,
        73.34      , 112.89      ,  95.94      ,  93.18      ,
        96.16      ,  94.11      , 110.455     , 108.75      ,
       107.64      , 108.28      , 105.64      , 117.46      ,
        91.43      , 107.885     , 112.94      ,  95.8       ,
       108.37      , 103.93      , 130.6       , 112.76      ,
       121.645     ,  90.82      , 100.05      , 109.05      ,
        98.86      , 111.1       ,  95.33      , 116.61      ,
        92.91      ,  89.72      ,  94.165     , 108.625     ,
       112.48      , 100.47      , 101.03      , 111.01      ,
       106.63      ,  97.21      , 115.05      , 105.64      ,
        88.22      ,  90.2       ,  98.14      , 147.72      ,
        92.09      ,  97.07      ,  77.64      ,  90.62      ,
       115.5       ,  76.22      ,  87.91      , 116.02      ,
        90.58      ,  94.91      ,  92.41      , 117.32      ,
        92.08      ,  77.225     , 106.        ,  98.28      ,
        87.53      ,  73.195     ,  90.58      , 118.74      ,
       101.27      , 124.31      ,  91.22      , 108.05      ,
        99.54      , 104.42      , 103.93      ,  88.9675    ,
        96.765     , 105.31      ,  89.05      , 101.97      ,
        96.14      , 107.885     , 103.67      ,  91.4       ,
       110.01      , 103.32      , 121.15      , 111.975     ,
        90.8       , 103.68      ,  98.03      , 105.67      ,
        97.14      ,  89.19      , 112.19      ,  99.69      ,
       111.19      , 105.53      ,  74.43      , 108.085     ,
        87.75      ,  87.        ,  90.39      , 134.26      ,
       104.34      ,  92.655     , 109.05      ,  93.36      ,
       102.04      ,  88.39      , 102.45      , 106.34      ,
       137.44      ,  96.99      ,  74.2       ,  88.23      ,
       115.45      , 128.94      , 111.17      ,  90.24      ,
        89.23      , 135.13      ,  97.33      ,  74.28      ,
        97.99      , 110.12      , 113.67      ,  88.14      ,
        94.345     ,  90.6       , 116.02      ,  90.27      ,
        90.58      , 110.76      ,  89.19      ,  92.38      ,
        87.44      , 125.72      , 111.05      , 108.76      ,
        77.16      , 100.47      , 100.68      , 100.77      ,
       102.935     ,  90.77      , 110.65      ,  97.76      ,
       100.83      ,  93.71      ,  88.3       ,  88.83      ,
        94.27      , 101.26      , 109.58      ,  90.04      ,
       100.71      ,  99.58      , 117.24      , 108.83      ,
        95.49      ,  92.48      ,  88.05      , 100.64      ,
        76.1       , 109.05      ,  94.69      ,  90.04      ,
        99.65      , 114.34      , 103.43      , 106.18      ,
        96.6       ,  99.38      , 101.96      ,  91.44      ,
       104.1       ,  88.69      , 111.1       , 112.67      ,
       104.42      , 110.6       , 103.11      ,  93.48      ,
        91.46      ,  91.88      , 108.99      ,  91.41      ,
        96.36      , 106.96      ,  93.97      , 101.71      ,
       102.39      ,  93.33      ,  86.98      ,  97.07      ,
        85.14      , 101.79      , 100.64      ,  92.98      ,
        93.96      ,  99.72      , 107.44      , 105.31      ,
        89.69      , 117.07      ,  91.385     ,  89.77      ,
        94.21      , 110.22      ,  88.6       , 105.25      ,
       100.35      , 117.65      , 108.96      ,  94.79      ,
       111.64      , 114.39      , 116.42      , 107.65      ,
        89.02      , 110.74      ,  88.88      ,  87.37      ,
        94.41      , 103.68      ,  73.24      ,  75.38      ,
       112.55      , 110.74      ,  85.97      ,  89.54      ,
        89.56      , 102.935     ,  89.62      ,  97.17      ,
        80.34      ,  91.3875    ,  89.6       , 110.91      ,
        89.24      ,  93.71      ,  96.21      ,  98.33      ,
       111.735     ,  89.99      ,  92.41      , 114.47      ,
        88.02      ,  92.22      , 109.21      , 107.82      ,
       108.85      ,  82.62      ,  94.95      , 111.155     ,
        95.5       , 102.89      ,  94.39      , 112.19      ,
       132.59      , 107.47      , 116.93      ,  99.98      ,
       108.01      , 108.53      , 107.76      ,  87.33      ,
       108.75      , 115.18      ,  88.63      , 111.12      ,
        88.52      ,  75.85      ,  98.72      ,  96.92      ,
       115.94      ,  87.3       ,  98.28      , 111.01      ,
       106.        ,  92.3       ,  89.83      ,  98.93      ,
        90.58      ,  91.38      ,  86.67      , 105.53      ,
       116.3       , 108.77      ,  77.41      , 111.91      ,
        90.155     ,  77.16      , 106.05      ,  96.765     ,
       109.05      , 128.58      , 110.47      , 103.08      ,
       109.05      ,  85.2       ,  90.66      ,  89.35      ,
        89.06      , 107.13      ,  84.22      ,  76.64      ,
        90.58      ,  89.65      , 101.18      , 100.5       ,
        91.56      , 127.91      , 103.01      ,  91.17      ,
        75.59      ,  78.01      , 109.48      ,  88.1       ,
        88.73      ,  92.09      , 128.8       ,  91.        ,
        93.12      , 112.57      , 105.82      , 108.77      ,
       116.02      , 109.11      , 113.91      , 119.08      ,
       102.91      ,  92.2375    ,  91.78      , 105.395     ,
       111.91      ,  90.57      , 114.55      , 100.11      ,
        94.11      , 118.27      , 102.83      ,  76.32      ,
        97.69      ,  98.1       ,  90.46      ,  89.29      ,
        88.39      ,  83.25      , 108.54      ,  89.12      ,
        93.59      ,  88.88      ,  94.345     , 106.18      ,
       111.62      ,  87.16      ,  88.78      ,  97.86      ,
        93.38      ,  95.27      , 103.62      , 103.47      ,
       105.53      , 111.65      , 100.77      ,  99.84      ,
        93.36      ,  92.2375    ,  86.04      , 100.77      ,
       105.29      , 111.41      ,  94.27      ,  90.69      ,
       117.07      ,  94.87      ,  87.37      ,  90.57      ,
        94.87      , 108.68      ,  89.4       ,  82.62      ,
        88.67      ,  91.44      , 100.09      , 129.        ,
       119.94      ,  88.9675    ,  92.08      ,  91.62      ,
        90.13      ,  89.05      , 115.05      ,  95.77      ,
        91.6       , 111.47      ,  92.83      , 123.705     ,
        90.62      ,  91.44      ,  87.47      ,  89.38      ,
       111.91      , 100.27      , 103.88      ,  92.73      ,
        88.69      ,  97.77      ,  86.77      ,  88.34      ,
        87.05      , 109.97      , 104.92      , 103.83      ,
        88.97      ,  88.38      ,  93.11      ,  96.85      ,
        94.1       , 123.69      ,  92.26      , 103.98      ,
        99.22      , 116.79      , 112.8       , 115.54333333,
       103.47      , 112.17      , 105.49      ,  88.63      ,
       103.91      ,  89.23      ,  92.2375    ,  90.99      ,
        95.56      ,  89.06      ,  88.7       , 117.27      ,
       102.5       ,  90.43      , 118.18      ,  75.42      ,
        99.55      ,  88.78      , 117.52      , 108.625     ,
       101.45      ,  93.15      ,  88.91      ,  92.19      ,
       121.28      , 105.53      ,  93.24      ,  89.96      ,
        93.93      ,  95.87      , 113.83      , 118.17      ,
        99.78      ,  88.91      ,  93.76      ,  87.58      ,
       117.65      ,  97.69      , 112.61      ,  99.54      ,
        87.63      , 109.05      ,  94.21      ,  87.63      ,
        93.67      , 103.47      , 110.6       ,  89.79      ,
        99.55      , 108.67      , 105.67      ,  84.56      ,
       105.65      ,  78.4       ,  98.84      , 104.92      ,
        98.57      , 120.38      ,  99.14      ,  94.21      ,
       105.64      , 103.82      , 111.08      , 112.76      ,
        88.38      ,  94.41      ,  91.4       ,  90.87      ,
       117.65      ,  93.        , 106.19      , 106.18      ,
       118.02      , 112.46      ,  90.22      , 103.03      ,
        91.99      , 107.5       , 114.22      ,  94.71      ,
       119.2       , 104.215     ,  88.98      , 121.165     ,
        89.        ,  98.5       , 111.91      ,  90.05      ,
        75.26      , 112.8       , 114.63      ,  91.17      ,
        91.99      ,  98.81      ,  93.77      ,  93.91      ,
        87.15      , 111.9       , 111.08      ,  90.45      ,
        93.64      ,  97.34      , 116.21      , 109.58      ,
        90.325     ,  93.71      , 110.55      ,  78.45      ,
        88.95      , 108.47      , 108.68      , 109.77      ,
        90.08      , 113.98      , 128.93      ,  93.21      ,
        99.39333333, 109.24      ,  90.96      , 106.89      ,
       102.795     ,  95.73      ,  97.96      ,  87.57      ,
        98.81      , 103.53      ,  93.08      , 103.62      ,
       121.65      ,  95.51      , 110.55      ,  89.06      ,
        98.07666667,  90.11      ,  90.44      , 106.77      ,
       110.71      , 110.71      , 108.88      , 108.06      ,
        75.26      , 113.83      ,  90.57      ,  89.        ,
        94.51      , 109.99      ,  89.09      ,  89.26      ,
       113.7       ,  79.99      , 105.395     ,  88.61      ,
       107.36      ,  96.16      , 109.93      , 112.86      ,
       103.88      ,  85.76      ,  93.59      , 104.01      ,
       110.63      ,  94.84      ])

In [29]:
dtree_reg.score(cat_encd_test_final,y_test)

0.2761630562713018

In [30]:
dtree_reg.score(cat_encd_train_final,y_train)

0.9780972728559386